"""add subscription_id to users

Revision ID: afeddd258647
Revises: 65b61a696796
Create Date: 2022-09-22 00:07:50.798945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afeddd258647'
down_revision = '65b61a696796'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'subscriptions', ['id'])
    op.add_column('users', sa.Column('subscription_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'users', 'subscriptions', ['subscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'subscription_id')
    op.drop_constraint(None, 'subscriptions', type_='unique')
    # ### end Alembic commands ###
