"""add subscription_end to users

Revision ID: cb62aaeac16c
Revises: afeddd258647
Create Date: 2022-09-22 00:21:22.928902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb62aaeac16c'
down_revision = 'afeddd258647'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_end', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_end')
    # ### end Alembic commands ###
